import { HomeLink } from "@/components/home-link";
import type { Metadata } from "next";
import { LegalLinks } from "@/components/legal-links";
import "../booking.css";

export const metadata: Metadata = { title: "Privacy policy — Arush Kukreja", description: "How Arush Kukreja’s call-booking service uses and handles your information." };
export default function BookingPrivacy() {
  return <main className="booking-page"><article className="booking-privacy"><a href="/book">← Back to booking</a><h1>Privacy policy</h1><p>When you book a call, your name, email address, chosen time, timezone, and discussion topic are sent to Arush Kukreja and Google Calendar to arrange the meeting and send a calendar invitation. Please do not include sensitive personal information in your message.</p><p>The website checks calendar availability and shows open times. It does not display Arush’s event titles, attendees, or other calendar details.</p><p>To prevent duplicate bookings, the website stores reservation times, a Google event identifier, and a keyed fingerprint of the request. It does not store your name, email, or message in its booking database. Reservation records are removed after their end time is more than 30 days in the past when availability is next checked. Google Calendar retains the event until the organizer deletes it.</p><p>Vercel performs automated browser checks to help prevent spam. Short-lived keyed hashes of your IP address and email address are used to limit booking attempts and availability requests. Rate-limit records expire within 48 hours and are removed on a subsequent availability check. These details are not added to a mailing list.</p><p>To cancel, reschedule, or request deletion of your booking information, email <a href="mailto:arushkukrejaa@gmail.com">arushkukrejaa@gmail.com</a>.</p></article><footer className="booking-footer"><HomeLink>Arush Kukreja</HomeLink><LegalLinks /></footer></main>;
}
